### ISSUE TITLE
Errors when compiling mod on v2021.4.14s

### ISSUE THREAD

**Issue by VanillaChan6571** [DaemonBeast/Unify#26]
4.0.0/4.0.1 Me stupid, and unable to load 

using HarmonyLib;
using UnityEngine;
using UnityEngine.UI;

despite me installing unity and others just to have it say no.

So Reactor Source pls? thanks.

**Comment by DaemonBeast** [comment]
@VanillaChan6571 Reactor is here: https://github.com/NuclearPowered/Reactor?

**Comment by VanillaChan6571** [comment]
> 
> 
> @VanillaChan6571 Reactor is here: https://github.com/NuclearPowered/Reactor?

I meant your mod source code to use reactor code.

**Comment by DaemonBeast** [comment]
@VanillaChan6571 My mod source code to use reactor code? Do you just mean my mod source code? It's available on the master branch isn't it? It may say `4.0.0` in the source code because I forgot to change the version.

**Comment by VanillaChan6571** [comment]
![ReactorIsntUnity](https://user-images.githubusercontent.com/39040261/115130880-820eca80-9fb0-11eb-8c1c-8275608d03df.PNG)
This is using Unity? Which I have no setup for unity. This isn't using reactor code. Unless reactor switched to unity. Which I heard nothing about it.

**Comment by DaemonBeast** [comment]
@VanillaChan6571 It does use Reactor. You just don't have Reactor set up properly as signified by that `The "GenerateReferences" task failed unexpectedly`.

I suspect that you have a 2021.4.14s copy of Among Us installed, which isn't properly supported by `Reactor.OxygenFilter` at the moment causing `GenerateReferences` to fail.

Mods compiled for 2021.4.12s work fine on 2021.4.14s and therefore, I have written some instructions on how to set up a 2021.4.12s copy of Among Us to use when compiling for 2021.4.14s: https://discord.com/channels/766765155136307250/785869972810367066/832910462458527744 (link to a collection of partially scattered messages on the Reactor Discord server).

**Comment by DaemonBeast** [comment]
I posted a nicer list of instructions here if you still need it: https://github.com/NuclearPowered/Reactor/issues/29#issuecomment-822761268.

**Comment by DaemonBeast** [comment]
An easier approach might be to change the mappings in the configuration file from `NuclearPowered/Mappings:0.4.0` to `XtraCube/Mappings:0.4.1`. You will also need to ensure that the configuration file contains the Among Us version `2021.4.14s` and you'll need to change the name of the Reactor dll in your game's plugins folder from `Reactor-2021.4.12s` to `Reactor-2021.4.14s`. Ensure you change your `AmongUs` environment variable back to the directory of your v2021.4.14s install as well if necessary.

**Comment by DaemonBeast** [comment]
It seems that the mappings were updated and they should now work for v2021.4.14s. No need to follow one of these solutions. Ensure the mappings are set to `NuclearPowered/Mappings:0.4.0`, game version is set to `2021.4.14s` and ensure you have the newest version of Reactor (https://github.com/NuclearPowered/Reactor/actions).
