### ISSUE TITLE
Incompatible with 2021.3.5s

### ISSUE THREAD

**Issue by DaemonBeast** [DaemonBeast/Unify#4]
**The mod is currently incompatible with Among Us 2021.3.5s.**

I'm working on a fix, but it's proving harder than expected due to the increased obfuscation and some weird quirks with some of the new code in the new Among Us update.

Hopefully I will get it to work soon.

**Comment by Mr-Fluuff** [comment]
I believe in you. It seems everyone is having the same problem trying to create custom server regions for the new update

**Comment by DaemonBeast** [comment]
@MrF1uff I'm pretty sure I have got it to work, but I'm not so sure if it's working fully since [Impostor](https://github.com/Impostor/Impostor) doesn't support 2021.3.5.

Do you think I should push the new changes now or wait till Impostor supports the new update so I can fully test the new changes?

**EDIT:** I'm probably going to push the new changes soon, as well as add a note in the README stating how the new version won't work yet.

**EDIT:** It seems I was mistaken; there is an Impostor version for 2021.3.5, but it's still in very early development and has to be built manually since there are no releases available.

**Comment by DaemonBeast** [comment]
I have updated the mod, but will leave this issue open in case there are any issues.

**Comment by Mr-Fluuff** [comment]
Sorry just now getting back to you. Yes nothing we can do untill impostor is fully implement in the new version I did however make my own build of impostor with a few tweaks and I was able to connect with your mod but impostor crashed so progress is definitely being made

**Comment by DaemonBeast** [comment]
@MrF1uff 😄 How exciting!

There might be some issues with my mod, so I'll definitely do some more testing, but it seems that the mod is somewhat functional.

Thanks for the information! ☺

**Comment by DaemonBeast** [comment]
@MrF1uff I finally got the code to work! 😄 I knew I was doing something wrong. 😅

Thanks for all the support! 😊👍
